# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages.proto',
  package='messages',
  syntax='proto3',
  serialized_pb=_b('\n\x0emessages.proto\x12\x08messages\"T\n\x0bTextMessage\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x66rom\x18\x02 \x01(\t\x12\n\n\x02to\x18\x03 \x01(\t\x12\x0c\n\x04\x62ody\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\x05\"\x1a\n\x0cMediaMessage\x12\n\n\x02id\x18\x01 \x01(\t\"E\n\x07Message\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\")\n\x04\x44\x61ta\x12\x0f\n\x0bTextMessage\x10\x00\x12\x10\n\x0cMediaMessage\x10\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_MESSAGE_DATA = _descriptor.EnumDescriptor(
  name='Data',
  full_name='messages.Message.Data',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TextMessage', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MediaMessage', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=170,
  serialized_end=211,
)
_sym_db.RegisterEnumDescriptor(_MESSAGE_DATA)


_TEXTMESSAGE = _descriptor.Descriptor(
  name='TextMessage',
  full_name='messages.TextMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='messages.TextMessage.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='from', full_name='messages.TextMessage.from', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='to', full_name='messages.TextMessage.to', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='body', full_name='messages.TextMessage.body', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='messages.TextMessage.timestamp', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=112,
)


_MEDIAMESSAGE = _descriptor.Descriptor(
  name='MediaMessage',
  full_name='messages.MediaMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='messages.MediaMessage.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=140,
)


_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='messages.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='messages.Message.command', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _MESSAGE_DATA,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=211,
)

_MESSAGE_DATA.containing_type = _MESSAGE
DESCRIPTOR.message_types_by_name['TextMessage'] = _TEXTMESSAGE
DESCRIPTOR.message_types_by_name['MediaMessage'] = _MEDIAMESSAGE
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE

TextMessage = _reflection.GeneratedProtocolMessageType('TextMessage', (_message.Message,), dict(
  DESCRIPTOR = _TEXTMESSAGE,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:messages.TextMessage)
  ))
_sym_db.RegisterMessage(TextMessage)

MediaMessage = _reflection.GeneratedProtocolMessageType('MediaMessage', (_message.Message,), dict(
  DESCRIPTOR = _MEDIAMESSAGE,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:messages.MediaMessage)
  ))
_sym_db.RegisterMessage(MediaMessage)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE,
  __module__ = 'messages_pb2'
  # @@protoc_insertion_point(class_scope:messages.Message)
  ))
_sym_db.RegisterMessage(Message)


# @@protoc_insertion_point(module_scope)
